local data = {};

data.animalsNames = {"Bunny", "Cat", "Cow", "Dog", "Mouse", "Sheep","Bat",
	"Bear",
	"Beawer",
	"Bird",
	"Camel",
	"Chicken",
	"Koala",
	"Crocodile",
	"Deer",
	"Duck",
	"Elephant",
	"Fox",
	"Hippo",
	"Lion",
	"Monkey",
	"Owl",
	"Pig",
	"Penguin",
	"Rabbit",
	"Shark",
	"Squirrel",
	"Tiger",
	"Whale"
}



data.animalsLocalized =
{
    ["bunny"] = "conejito",
    ["cat"] = "gato",
    ["cow"] = "vaca",
    ["dog"] = "perro",
    ["mouse"] = "ratón",
    ["sheep"] = "oveja",
    ["bat"] = "bate",
    ["bear"] = "oso",
    ["beawer"] = "castor",
    ["bird"] = "pájaro",
    ["camel"] = "camello",
    ["chicken"] = "pollo",
    ["koala"] = "koala",
    ["crocodile"] = "cocodrilo",
    ["deer"] = "ciervo",
    ["duck"] = "pato",
    ["elephant"] = "elefante",
    ["fox"] = "zorro",
    ["hippo"] = "hipopótamo",
    ["lion"] = "león",
    ["monkey"] = "mono",
    ["owl"] = "búho",
    ["pig"] = "cerdo",
    ["penguin"] = "pingüino",
    ["rabbit"] = "conejo",
    ["shark"] = "tiburón",
    ["squirrel"] = "ardilla",
    ["tiger"] = "tigre",
    ["whale"] = "ballena",
}

data.animalsDescriptions = {
	"Little Peter Rabbit had a fly upon his nose,\nLittle Peter Rabbit had a fly upon his nose,\nLittle Peter Rabbit had a fly upon his nose,\nAnd he flipped it and he flapped it and it flew away. ", 
	"Soft kitty, warm kitty\nLittle ball of fur.\nLazy kitty, pretty kitty,\nPurr, purr, purr..", 
	"The friendly cow, all red and white,\nI love with all my heart:\nShe gives me cream with all her might,\nTo eat with apple tart.", 
	"Little ears as soft as silk\nLittle teeth as white as milk\nLittle noses cool and pink,\nLittle eyes that blink and blink,\nLittle bodies round and fat,\nLittle hearts that pit-a-pat!", 
	"A mouse in the grass ran about,\nStopping by the water spout.\nNibbling on something I could barely see,\nAnd didn’t seem to notice me.", 
	"Baa, baa, black sheep\nHave you any wool?\nYes sir, yes sir\nThree bags full.\nOne for my master\nAnd one for the dame\nOne for the little boy\nWho lives down the lane."
};
data.animalsImages = {
	"images/bunny.png",
	"images/cat.png", 
	"images/cow.png",
	"images/dog.png", 
	"images/mouse.png", 
	"images/sheep.png",
	"images/animals/bat.png",
	"images/animals/bear.png",
	"images/animals/beawer.png",
	"images/animals/bird.png",
	"images/animals/camel.png",
	"images/animals/chicken.png",
	"images/animals/koala.png",
	"images/animals/crocodile.png",
	"images/animals/deer.png",
	"images/animals/duck.png",
	"images/animals/elephant.png",
	"images/animals/fox.png",
	"images/animals/hippo.png",
	"images/animals/lion.png",
	"images/animals/monkey.png",
	"images/animals/owl.png",
	"images/animals/pig.png",
	"images/animals/penguin.png",
	"images/animals/rabbit.png",
	"images/animals/shark.png",
	"images/animals/squirrel.png",
	"images/animals/tiger.png",
	"images/animals/whale.png"
};
data.foodsImages = {
	"images/carrot.png",
	"images/milk.png",
	"images/seno.png",
	"images/bone.png",
	"images/cheese.png",
	"images/grass.png",
};

data.animalsSounds = {
	"sounds/bunny.mp3",
	"sounds/cat.mp3",
	"sounds/cow.mp3",
	"sounds/dog.mp3",
	"sounds/mouse.mp3",
	"sounds/sheep.mp3",
	"sounds/bat.mp3",
	"sounds/bear.mp3",
	"sounds/beawer.mp3",
	"sounds/bird.mp3",
	"sounds/camel.mp3",
	"sounds/chicken.mp3",
	"sounds/koala.mp3",
	"sounds/crocodile.mp3",
	"sounds/deer.mp3",
	"sounds/duck.mp3",
	"sounds/elephant.mp3",
	"sounds/fox.mp3",
	"sounds/hippo.mp3",
	"sounds/lion.mp3",
	"sounds/monkey.mp3",
	"sounds/owl.mp3",
	"sounds/pig.mp3",
	"sounds/penguin.mp3",
	"sounds/rabbit.mp3",
	"sounds/shark.mp3",
	"sounds/squirrel.mp3",
	"sounds/tiger.mp3",
	"sounds/whale.mp3"
}

return data;